---
run:
  # If it is explicitly set to 0 (i.e. not the default) then golangci-lint will automatically set the value to match Linux container CPU quota.
  concurrency: 0
  timeout: 5m
  issues-exit-code: 2
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

linters:
  disable-all: true
  enable:
    - depguard
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - typecheck
    # - asciicheck
    # - bodyclose
    # - dogsled
    # - dupl
    # - errcheck
    # - errorlint
    # - exhaustive
    # - exhaustivestruct
    # - exportloopref
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    # - gofumpt
    # - goheader
    # - golint
    # - gomnd
    # - gomodguard
    # - goprintffuncname
    # - gosec (gas)
    - gosimple  # (megacheck)
    # - interfacer
    # - lll
    # - maligned
    # - nestif
    # - nlreturn
    # - noctx
    # - nolintlint
    - revive
    # - rowserrcheck
    # - scopelint
    # - sqlclosecheck
    - staticcheck
    - stylecheck
    # - testpackage
    # - tparallel
    - unconvert
    # - unparam
    - unused
    # - whitespace
    # - wrapcheck
    # - wsl
linters-settings:
  gocritic:
    enabled-checks:
      # Diagnostic
      - appendAssign
      - argOrder
      - badCond
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagDeref
      - flagName
      - nilValReturn
      - offBy1
      - sloppyReassign
      - weakCond
      - octalLiteral

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy

      # Style
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - docStub
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc
      - yodaStyleExpr

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnamedResult
      - unnecessaryBlock

  depguard:
    rules:
      main:
        files:
          - "$all"
#        allow:
#          - $gostd
        deny:
          - pkg: "github.com/hashicorp/golang-lru"
            desc: "Do not allow direct use of IBM patented NewARC"
          - pkg: "github.com/sirupsen/logrus"
            desc: "we use Zerolog"
          - pkg: "github.com/bugsnag/bugsnag-go"
            desc: "we use Sentry"
          - pkg: "github.com/pkg/errors"
            desc: "should be replaced by standard lib errors package"

      pkg:
        files:
          - "**/pkg/**/*.go"
        deny:
          - pkg: "github.com/spf13"
            desc: "pkg must not depend on cobra or pflag"
          - pkg: "github.com/containerd/nerdctl/v2/cmd"
            desc: "pkg must not depend on cmd files"

issues:
  exclude-rules:
    - linters:
        - revive
      text: "unused-parameter"
