---
output:
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  # FIXME
  exclude-rules:
    - linters:
        - revive
      text: "unused-parameter"

run:
  concurrency: 0
  timeout: 5m
  issues-exit-code: 2
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

linters:
  disable-all: false
  enable-all: true
  disable:
    # Opting-out
    - nonamedreturns  # named returns are occasionally useful
    - exhaustruct  # does not serve much of a purpose
    - funlen  # not interested
    - cyclop  # not interested much
    - godox  # having these are useful

    # Duplicating
    - gci  # we use go-imports instead

    # Deprecated
    - tenv

    # Temporarily disabling
    - usetesting

    # To be enabled
    - wrapcheck
    - wsl
    - nlreturn
    - gochecknoglobals
    - godot
    - lll
    - varnamelen
    - thelper
    - protogetter
    - gosec
    - err113
    - gofumpt
    - exhaustive
    - musttag
    - paralleltest
    - testpackage
    - nestif
    - contextcheck
    - gocyclo
    - forcetypeassert
    - gocognit
    - errcheck
    - dupl
    - whitespace
    - mnd
    - ireturn
    - nilnil
    - tparallel
    - tagliatelle
    - goconst
    - maintidx

linters-settings:
  staticcheck:
    checks:
      - "all"

  gocritic:
    disabled-checks:
      - appendAssign
      - ifElseChain

  depguard:
    rules:
      main:
        files:
          - $all
          - "!**/leptonic/**/*"
        # list-mode: strict
        deny:
          - pkg: "github.com/hashicorp/golang-lru"
            desc: "Do not allow direct use of IBM patented NewARC"
          - pkg: "github.com/sirupsen/logrus"
            desc: "we use Zerolog"
          - pkg: "github.com/bugsnag/bugsnag-go"
            desc: "we use Sentry"
          - pkg: "github.com/pkg/errors"
            desc: "should be replaced by standard lib errors package"
          - pkg: "github.com/opencontainers"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/containerd/cgroups"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/containerd/containerd/v2/contrib/apparmor"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/containerd/containerd/v2/contrib/seccomp"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/distribution"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/fluent"
          - pkg: "github.com/Microsoft/hcsshim"
          - pkg: "github.com/Microsoft/go-winio"
          # - pkg: "github.com/vishvananda"
      no-patent:
        files:
          - $all
        deny:
          - pkg: "github.com/hashicorp/golang-lru/arc/v2"
            desc: "patented (https://github.com/hashicorp/golang-lru/blob/arc/v2.0.7/arc/arc.go#L18)"

      pkg:
        files:
          - "**/pkg/**/*.go"
        deny:
          - pkg: "github.com/spf13"
            desc: "pkg must not depend on cobra or pflag"
          - pkg: "go.farcloser.world/lepton/cmd"
            desc: "pkg must not depend on cmd files"
