# https://pkg.go.dev/sigs.k8s.io/kind/pkg/apis/config/v1alpha4#Cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: _output/lepton
        containerPath: /usr/local/bin/lepton
      - hostPath: /tmp/go
        containerPath: /usr/local/go
      - hostPath: .
        containerPath: /source
      - hostPath: /opt/cni
        containerPath: /opt/cni
