name: build

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  env:
    uses: ./.github/workflows/environment.yml

  build:
    needs: env
    timeout-minutes: ${{ fromJSON(needs.env.outputs.TIMEOUT_SHORT) }}
    name: go ${{ matrix.go }} | ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ${{ needs.env.outputs.RUNNER_WINDOWS_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_AMD64_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_ARM64_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_WINDOWS_CANARY }}
            go: ${{ needs.env.outputs.GO_CANARY }}
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_CANARY }}
            go: ${{ needs.env.outputs.GO_CANARY }}

    steps:
      - name: "Clone"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: "Setup"
        uses: ./.github/actions/node
        with:
          go: ${{ matrix.go }}
      - name: "Building"
        run: |
          GOOS=linux GOARCH=amd64 make build
          GOOS=linux GOARCH=arm64 make build
          GOOS=windows make build
