name: unit

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  env:
    uses: ./.github/workflows/environment.yml

  unit:
    needs: env
    timeout-minutes: ${{ fromJSON(needs.env.outputs.TIMEOUT_SHORT) }}
    name: go ${{ matrix.go }} | ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ${{ needs.env.outputs.RUNNER_WINDOWS_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_CANARY }}
            go: ${{ needs.env.outputs.GO_CANARY }}

    steps:
      - name: "Clone"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: "Setup"
        uses: ./.github/actions/node
        with:
          go: ${{ matrix.go }}
      # FIXME: caching? Takes ~30s
      - name: "Setup CNI"
        run: |
          [ "$RUNNER_OS" != Windows ] || GOPATH=$(go env GOPATH) ./hack/provisioning/windows/cni.sh
      - name: "Unit testing"
        run: |
          make test-unit
